### ISSUE TITLE
Combobox X11 at wrong position with window decorations in awesomeWM

### ISSUE THREAD

**Issue by ventosus** [brummer10/GxPlugins.lv2#31] opened 2021-02-02 20:17 UTC
Well, the screenshot says it all.

In Ardour, the combobox X11 window shows up at the wrong spot with window decorations.

In Qtractor, the combobox X11 window shows up at the right spot, but with window decorations, too.

Something may be off with window hints, etc. there.

![2021-02-02-211045_3840x1080_scrot](https://user-images.githubusercontent.com/1863184/106656840-81fb5300-659b-11eb-94a0-039bc9a44cc7.png)

**Comment by ventosus** [comment] 2021-02-02 20:18
This is with gxplugins.lv2 0.8-1

**Comment by ventosus** [comment] 2021-02-02 20:23
Has been reproduced by @diovudau, so I'm not the only one experiencing this.

**Comment by brummer10** [comment] 2021-02-06 05:08
Hi
Thanks for reporting. 
I wonder if the same happen with Fluida. The guitarix LV2 plugins using a older version of libxputty, so it may be that I've fixed that already there but haven't forward the fix to guitarix. 
If Fluida works without this issue on your system, I could easily fix it. 

regards
hermann

**Comment by brummer10** [comment] 2021-02-06 07:59
I've pushed a fix for it to guitarix, as the issue is related to guitarix, not to GxPlugins. (GxPlugins don't use combo-boxes at all)

**Comment by ventosus** [comment] 2021-02-06 11:43
> I wonder if the same happen with Fluida

Combobox in Fluida works fine.

> I've pushed a fix for it to guitarix, as the issue is related to guitarix, not to GxPlugins. (GxPlugins don't use combo-boxes at all)

Ah, sorry, didn't know that those were separate projects.

**Closed as completed** 2021-04-24 15:34 UTC
