### ISSUE TITLE
Plugin automations should provide discrete on/off for bypass and rename it to "enable"

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/GxPlugins.lv2#10] opened 2018-12-09 16:32 UTC
These FOSS Gx plugins are amazing and I'm hugely grateful for your talent and work on them. It's a big piece of the puzzle for a project I'm working on.

A couple of frustrations I've found though:

1. If the automation is on/off (like bypass, but also things like looper rec/play), then the plugin should expose a "discrete" drawing ability in the automation lane. Instead, I'm awkwardly trying to put two dots right next to each other, one for 0 and the other for 1 (or vice versa) and getting a line that is almost vertical but not quite and is imprecise (which matters for things like looping). 

2. Many of these Gx plugins have a bypass, which is great, but the labeling is confusing. In them, bypass 0 = pedal off and bypass 1 = pedal on, which is correct, but since it's labeled "bypass" instead of "enable", that's confusing. "Bypass false (0)" intuitively means "on" and "Bypass true (1)" intuitively means "off". 

Check out the "a-Delay" plugin from Ardour. Its bypass is labeled as "enable" to make it less confusing and the "enable" function exposes a discrete drawing ability in the automation lane for better toggling precision.

Edit: Ahh, here's the reason. See this response from the Ardour team. https://discourse.ardour.org/t/enable-discrete-mode-for-audio-track-plugin-automation/100039

**Comment by brummer10** [comment] 2018-12-09 19:14
Hi

Thanks for reporting the issue.
I've pushed a fix for it now, please update your checkout and let me know if the issue is solved.

regards
hermann

**Closed as completed** 2018-12-11 19:31 UTC
